
#更改个人数据库配置
blog:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: selab_blog
    username: root
    password: 456321
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 2